### ISSUE TITLE
snmp_new_v3_session:Unsupported privacy protocol(DES)

### ISSUE THREAD

**Issue by zdudic** [ansible-collections/ansible.snmp#29]
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```

ansible-core 2.12 with ansible.snmp 1.2.0 

ansible-core 2.14 with ansible.snmp 2.0.0 


```

##### COLLECTION VERSION

```
all three, 1.2.0 and 2.0.0

```

##### CONFIGURATION

```
COLOR_ERROR(/home/.ansible.cfg) = red
COLOR_VERBOSE(/home/.ansible.cfg) = white
COLOR_WARN(/home/.ansible.cfg) = bright purple
DEFAULT_GATHERING(/home/.ansible.cfg) = explicit
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/.ansible.cfg) = True
DEFAULT_LOG_PATH(/home/.ansible.cfg) = /tmp/ansible.log
DEFAULT_ROLES_PATH(/home/.ansible.cfg) = ['/home/etc-roles>
DEFAULT_TIMEOUT(/home/.ansible.cfg) = 30
DEPRECATION_WARNINGS(/home/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/.ansible.cfg) = False
INTERPRETER_PYTHON(/home/.ansible.cfg) = auto_silent
INVENTORY_ENABLED(/home/.ansible.cfg) = [ 'nmap', 'host_list', 'script', 'yaml', 'ini']


```

##### OS / ENVIRONMENT

RHEL or Oracle Linux 9

##### STEPS TO REPRODUCE

The task that fails read this code

```
- name: Gather SNMP v3 facts
  connection: ansible.snmp.v3_usm
  vars:
    host: "{{ hostname }}"
    sec_level: authPriv
    version: 3
    username: "{{ snmpv3_user }}"
    auth_proto: SHA1
    auth_pass: "{{ _authpasswd }}"
    priv_proto: AES128
    priv_pass: "{{ _privpasswd }}"
  ansible.snmp.get:
    oids:
      - oid: "SNMPv2-MIB::sysName.0"
      - oid: "SNMPv2-MIB::sysLocation.0"
        
  # ignore_errors: true
  register: _snmp1_facts

```

##### EXPECTED RESULTS

```
Expected is to receive snmp system name and location.
```
##### ACTUAL RESULTS

```
error
snmp_new_v3_session:Unsupported privacy protocol(DES)

```

**Comment by Andyjb8** [comment]
I am getting  a similar error:

Here is my task:

```
    - name: Test SNMPv3 credentials using ansible.snmp.walk (direct test)
      ansible.snmp.walk:
        oids:
          - oid: "1.3.6.1.2.1.1.1.0"
      vars:
        ansible_connection: ansible.snmp.v3_usm
        ansible_host: "{{ target_device_ip }}"
        ansible_snmp_username: "{{ snmpv3_user }}"
        ansible_snmp_auth_key: "{{ snmpv3_auth_pass }}"
        ansible_snmp_auth_protocol: "{{ snmpv3_auth }}{{ snmpv3_auth_level }}"
        ansible_snmp_priv_key: "{{ snmpv3_priv_pass }}"
        ansible_snmp_priv_protocol: "{{ snmpv3_priv }}{{ snmpv3_priv_level }}"
        ansible_snmp_security_level: authPriv
        ansible_snmp_context: ""
      register: snmpv3_direct_test_result
      delegate_to: localhost
      failed_when: false
```

Here is what I get:
```
TASK [Test SNMPv3 credentials using ansible.snmp.walk] *************************************************************************************************
task path: /home/admin/automation/playbooks/Solarwinds/shared_tasks/orion_task_validate_snmpv3_credentials.yml:17
Friday 18 July 2025  17:08:49 +0000 (0:00:00.208)       0:00:01.180 *********** 
error:snmp_new_v3_session:Unsupported privacy protocol(DES)
error:v3_session: couldn't open SNMP session().
ESTABLISHED SNMP v3 CONNECTION: <IP_ADDRESS>
ok: [localhost] => {
    "changed": false,
    "elapsed": {
        "total": 0.00013136863708496094,
        "walk": 0.00013136863708496094
    },
    "failed_when_result": false,
    "msg": "<built-in function walk> returned a result with an error set"
}
```

SNMP walk with the same credentials works!
```
snmpwalk -v3 -u <user> -l authPriv -a SHA -A "AUTH_PASSWORD" -x AES -X "PRIV_PASSWORD" <IP_ADDRESS>:161 1.3.6.1.2.1.1.1.0
SNMPv2-MIB::sysDescr.0 = STRING: Juniper Networks, Inc. vsrx internet router, kernel JUNOS 20.3R1.8, Build date: 2020-09-21 08:40:37 UTC Copyright (c) 1996-2020 Juniper Networks, Inc.
```


Here are my ansible, ansible.snmp and net-snmp package versions:
```
ansible [core 2.15.12]
  config file = /home/admin/ansible.cfg
  configured module search path = ['/home/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/admin/automation/collections:/usr/share/ansible/collections
  executable location = /home/admin/.local/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

ansible.snmp                  3.0.0  

net-snmp-libs-5.9.1-17.el9.x86_64
net-snmp-utils-5.9.1-17.el9.x86_64
net-snmp-agent-libs-5.9.1-17.el9.x86_64
net-snmp-5.9.1-17.el9.x86_64
python3-net-snmp-5.9.1-17.el9.x86_64
```
